### PR TITLE
One counter bug fix

### LINKED ISSUE #4: Support counters that contains only 1 counter per instance
These counters have a different format and will probably cause the code to crash now

### PR DESCRIPTION
**Pull request by ghsi011**
Closes #4

### CODE REVIEW

File: RegistryPerformanceViewerLib-Test/test.cpp [hunk 1]
```diff
@@ -25,3 +25,14 @@ TEST(TestCounterData, Print)
 	const CounterData counter_data(L"230");
     print(counter_data.instances());
 }
+
+TEST(TestCounterData, OneCounter)
+{
+    const std::wstring counter_name = L"Browser";
+	const CounterNames counters;
```
Comment (Eran-YT) [inline RegistryPerformanceViewerLib-Test/test.cpp]: Fix indents

File: RegistryPerformanceViewerLib-Test/test.cpp [hunk 2]
```diff
@@ -25,3 +25,14 @@ TEST(TestCounterData, Print)
...
+
+	const CounterData counter(counters.counter_id(counter_name));
+
+    EXPECT_TRUE(!counter.instances().empty());
```
Comment (Eran-YT) [inline RegistryPerformanceViewerLib-Test/test.cpp]: EXPECT_FALSE

File: RegistryPerformanceViewerLib/CounterData.cpp [hunk 3]
```diff
@@ -104,6 +112,21 @@ PerfInstance CounterData::parse_instance(uint32_t& current_index,
     return instance;
 }
 
+PerfInstance CounterData::parse_single_instance(uint32_t& current_index,
+	const std::vector<Counter>& counters_template) const
```
Comment (Eran-YT) [inline RegistryPerformanceViewerLib/CounterData.cpp]: Fix indents

File: RegistryPerformanceViewerLib/CounterData.cpp [hunk 4]
```diff
@@ -26,8 +26,16 @@ PerfInstances CounterData::instances() const
         uint32_t current_index = current_object_index + object_type->HeaderLength;
         std::vector<Counter> counters = parse_counter_definitions(current_index, object_type);
 
-        for (LONG current_instance = 0; current_instance < object_type->NumInstances; current_instance++) {
-            instances.push_back(parse_instance(current_index, counters));
+        if(object_type->NumInstances == PERF_NO_INSTANCES)
+        {
+            instances.push_back(parse_single_instance(current_index, counters));
+        }
+        else
```
Comment (Eran-YT) [inline RegistryPerformanceViewerLib/CounterData.cpp]: } else {

File: RegistryPerformanceViewerLib/CounterData.cpp [hunk 5]
```diff
@@ -26,8 +26,16 @@ PerfInstances CounterData::instances() const
...
+        {
+            for (LONG current_instance = 0; current_instance < object_type->NumInstances; current_instance++)
```
Comment (Eran-YT) [inline RegistryPerformanceViewerLib/CounterData.cpp]: { in same line as for

**Review by Eran-YT — CHANGES_REQUESTED** [review]

**Review by Eran-YT — APPROVED** [review]
